apiVersion: v1 
kind: Service 
metadata:
  name: order-app-service
  namespace: ecommerce-dev
spec: 
  type: ClusterIP

  selector:
    appname: order-service-deployment

  ports:
    - port: 8083
      targetPort: 8083
      protocol: TCP   
  